version: "3"
services:
  nginx:
    image: nginx:1.21.1
    restart: unless-stopped
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - /mnt/volume_sgp1_01/data/certbot/conf:/etc/letsencrypt
      - /mnt/volume_sgp1_01/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:v1.17.0
    restart: unless-stopped
    volumes:
      - /mnt/volume_sgp1_01/data/certbot/conf:/etc/letsencrypt
      - /mnt/volume_sgp1_01/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mongo:
    image: faysalahmad/idreesia-db
    volumes:
      - /mnt/volume_sgp1_01/data:/data/db
      - /mnt/volume_sgp1_01/backup:/data/backup

  mongo-express:
    image: faysalahmad/idreesia-mongo-express
    ports:
      - "3003:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=erp-admin
      - ME_CONFIG_BASICAUTH_PASSWORD=fairly long password
    depends_on:
      - mongo

  web:
    image: faysalahmad/idreesia-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mobile:
    image: faysalahmad/idreesia-mobile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  jobs:
    image: faysalahmad/idreesia-jobs
    ports:
      - "3002:3002"
    depends_on:
      - mongo
