version: "3"
services:
  mongo:
    image: faysalahmad/idreesia-db
    volumes:
      - /mnt/volume_sgp1_01/data:/data/db
      - /mnt/volume_sgp1_01/backup:/data/backup

  mongoexpress:
    image: faysalahmad/idreesia-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=erp-admin
      - ME_CONFIG_BASICAUTH_PASSWORD=fairly long password
    depends_on:
      - mongo

  web:
    image: faysalahmad/idreesia-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mobile:
    image: faysalahmad/idreesia-mobile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  jobs:
    image: faysalahmad/idreesia-jobs
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  caddy:
    image: caddy:2.6.1-alpine
    restart: unless-stopped
    depends_on:
      - web
      - jobs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/caddy:/etc/caddy
