version: "3"
services:
  nginx:
    image: faysalahmad/idreesia-nginx
    ports:
      - "80:80"

  mongo:
    image: faysalahmad/idreesia-db
    volumes:
      - ./data/mongo:/data/db
      - ~/Dropbox/Idreesia-ERP-Backup:/data/backup

  mongo-express:
    image: faysalahmad/idreesia-mongo-express
    ports:
      - "3002:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=erp-admin
      - ME_CONFIG_BASICAUTH_PASSWORD=fairly long password
    depends_on:
      - mongo

  web:
    image: faysalahmad/idreesia-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mobile:
    image: faysalahmad/idreesia-mobile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  jobs:
    image: faysalahmad/idreesia-jobs
    ports:
      - "3002:3002"
    depends_on:
      - mongo
