version: "3"
services:
  mongo:
    image: faysalahmad/idreesia-db
    volumes:
      - ./data/mongo:/data/db
      - ~/Dropbox/Idreesia-ERP-Backup:/data/backup

  web:
    image: faysalahmad/idreesia-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mobile:
    image: faysalahmad/idreesia-mobile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  jobs:
    image: faysalahmad/idreesia-jobs
    ports:
      - "3002:3002"
    depends_on:
      - mongo
